# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Welcomi < Formula
  desc ""
  homepage "https://github.com/miyasasa/welcomi"
  version "0.0.5"

  on_macos do
    url "https://github.com/miyasasa/welcomi/releases/download/v0.0.5/welcomi_0.0.5_darwin_all.tar.gz"
    sha256 "de195784ae8913fcec256ba50aa2d58bc2222832fcb5572d3c0700c7d3c2e590"

    def install
      bin.install "welcomi"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.5/welcomi_0.0.5_linux_arm64.tar.gz"
      sha256 "52bd2f6570c9a308e505eb89d4a319d0d2b406d81c08d4d9dbcdcbfe984b17ed"

      def install
        bin.install "welcomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.5/welcomi_0.0.5_linux_amd64.tar.gz"
      sha256 "36c4df47a8f215fe72e19baa780d7db7cecaf8bd952bbf796a9a5a3db8f85b14"

      def install
        bin.install "welcomi"
      end
    end
  end
end
