# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Welcomi < Formula
  desc ""
  homepage "https://github.com/miyasasa/welcomi"
  version "0.0.8"

  on_macos do
    url "https://github.com/miyasasa/welcomi/releases/download/v0.0.8/welcomi_0.0.8_darwin_all.tar.gz"
    sha256 "8390ae3179d0b4dd88caa260bea07a95b12bd5161f242f700b8b76eb653afbf0"

    def install
      bin.install "welcomi"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.8/welcomi_0.0.8_linux_arm64.tar.gz"
      sha256 "5ec118479b3ffcaa5054b63779c4cfbd4e01aa0d516340d592dbeb8b4757b05c"

      def install
        bin.install "welcomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.8/welcomi_0.0.8_linux_amd64.tar.gz"
      sha256 "14082af72f18687036b112ed52449d5a999894bd037f33e8f9c5127c61107a79"

      def install
        bin.install "welcomi"
      end
    end
  end
end
