# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Welcomi < Formula
  desc ""
  homepage "https://github.com/miyasasa/welcomi"
  version "0.0.1"

  on_macos do
    url "https://github.com/miyasasa/welcomi/releases/download/v0.0.1/welcomi_0.0.1_darwin_all.tar.gz"
    sha256 "93d5b68796f4a4bf2b1baa90f05f35ca7507f29bd5b897d377e18073be62cb65"

    def install
      bin.install "welcomi"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.1/welcomi_0.0.1_linux_arm64.tar.gz"
      sha256 "0d8271d0da9076f6a60667796af25fe60ec7f12aa1b68223766de10c464b545b"

      def install
        bin.install "welcomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.1/welcomi_0.0.1_linux_amd64.tar.gz"
      sha256 "0d8271d0da9076f6a60667796af25fe60ec7f12aa1b68223766de10c464b545b"

      def install
        bin.install "welcomi"
      end
    end
  end
end
