# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Welcomi < Formula
  desc ""
  homepage "https://github.com/miyasasa/welcomi"
  version "0.0.3"

  on_macos do
    url "https://github.com/miyasasa/welcomi/releases/download/v0.0.3/welcomi_0.0.3_darwin_all.tar.gz"
    sha256 "405ec0ea05e52efce8223efe63b0bb37ac0ae443b78e4764c0ab61068de31a3e"

    def install
      bin.install "welcomi"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.3/welcomi_0.0.3_linux_arm64.tar.gz"
      sha256 "9a1e5d9c0d56f26991a2f8117d829c4a2f9133b377f4850bf1225580f9c1b467"

      def install
        bin.install "welcomi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/miyasasa/welcomi/releases/download/v0.0.3/welcomi_0.0.3_linux_amd64.tar.gz"
      sha256 "9a1e5d9c0d56f26991a2f8117d829c4a2f9133b377f4850bf1225580f9c1b467"

      def install
        bin.install "welcomi"
      end
    end
  end
end
